name: ordem_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^16.2.0
  http: ^1.4.0
  provider: ^6.1.5
  riverpod: ^2.6.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_multi_formatter: ^2.7.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6 

flutter:
  uses-material-design: true
  assets:
    - assets/pencil.png
    - assets/robo_quebrado.jpg
    - assets/OrdemPRO-Icone.png
    - assets/OrdemPRO-LogoTransparente.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/OrdemPRO-Icone.png"

flutter_native_splash:
  color: "#ffffff"         
  image: assets/OrdemPRO-LogoTransparente.png
  android: true
  ios: true